"""Walk-forward validation — the trustworthy way to read a backtest result.

``engine.run_backtest()`` alone answers "how did params X perform on data
that X was (explicitly, via ``backtest run --sweep``, or implicitly, via
git-history tuning) chosen from?" That number is contaminated by in-sample
selection — every live parameter change in CLAUDE.md §10.2 (stop/take,
day_change band, ma_discount, entry_mode itself) was picked by looking at
results on exactly this cached window. More candidate grids tried == higher
probability the "winner" is noise, not edge (Bailey & López de Prado's
Probability of Backtest Overfitting framing).

This module answers the harder, honest question instead: "how would these
rules have performed on data NOT used to pick them?"

Two building blocks:

  split_by_date(series, cutoff)
      One shared calendar cutoff across the whole universe (not a
      per-symbol fraction) — every symbol's train/test split refers to the
      same historical period, so a fold never mixes one symbol's 2025 data
      with another's 2026 data.

  walk_forward(series, param_grid, ...)
      Rolls a train/test window forward across the full history. For each
      fold: grid-search ``param_grid`` on the train slice only (pick by
      expectancy_pct), then run the winning params UNCHANGED on the test
      slice. Every fold's test trades are concatenated into one combined
      out-of-sample trade list — THAT is the number to trust, because no
      trade in it was generated by params chosen while looking at that
      same trade. ``walk_forward_efficiency`` (OOS/IS expectancy ratio)
      flags whether the in-sample edge survives contact with unseen data.

Two honesty limits this does NOT remove:
  - Sample size still matters. A fold's test_summary with a handful of
    trades is not more meaningful than the same handful was in
    ``engine.Result.summary()`` — read n before trusting expectancy (100+
    trades before treating an edge as real; see backtest module docstring).
  - The universe is fixed and small (30 KOSPI large-caps, ~2.5y of daily
    bars — see backtest/data.py). Walk-forward reduces in-sample selection
    bias; it cannot manufacture regime diversity or trade count the
    underlying cache doesn't have. A strategy that has only ever traded
    through one bull regime has not been tested against a bear regime,
    walk-forward or not.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from statistics import mean

from .engine import (
    Params,
    Result,
    Trade,
    normalize_rows,
    run_backtest,
    simulate_exits,
)


def _bar_date(bar: dict) -> str:
    return str(bar.get("dt") or bar.get("date") or "")


def date_bounds(series: dict[str, list[dict]]) -> tuple[str, str]:
    """Earliest and latest bar date across the whole universe (empty → "")."""
    dates = [_bar_date(b) for bars in series.values() for b in bars if _bar_date(b)]
    return (min(dates), max(dates)) if dates else ("", "")


def split_by_date(
    series: dict[str, list[dict]], cutoff: str
) -> tuple[dict[str, list[dict]], dict[str, list[dict]]]:
    """Split every symbol's bars at one shared calendar cutoff (YYYYMMDD).

    Bars with date < cutoff go to train; date >= cutoff go to test. A
    would-be trade whose entry straddles the boundary just doesn't fire in
    either half — ``backtest_symbol`` never looks past its own bar list, so
    this is "the strategy wasn't running" for a few days at the seam, not a
    data leak. Symbols with no bars on one side are omitted from that side.
    """
    train: dict[str, list[dict]] = {}
    test: dict[str, list[dict]] = {}
    for code, bars in series.items():
        t_bars = [b for b in bars if _bar_date(b) and _bar_date(b) < cutoff]
        v_bars = [b for b in bars if _bar_date(b) and _bar_date(b) >= cutoff]
        if t_bars:
            train[code] = t_bars
        if v_bars:
            test[code] = v_bars
    return train, test


def _slice_dates(
    series: dict[str, list[dict]], start_date: str, end_date: str
) -> dict[str, list[dict]]:
    out: dict[str, list[dict]] = {}
    for code, bars in series.items():
        rows = [b for b in bars if start_date <= _bar_date(b) <= end_date]
        if rows:
            out[code] = rows
    return out


def _pick_best(
    series: dict[str, list[dict]], param_grid: list[Params]
) -> tuple[Params, dict]:
    """Grid-search ``param_grid`` on ``series``, selecting by expectancy_pct.

    Falls back to ``param_grid[0]`` (treat it as the incumbent — pass the
    current live params first) when nothing traded, so a fold with too
    little train data to discriminate doesn't silently drift to an
    untested corner of the grid.
    """
    best: Params | None = None
    best_summary: dict | None = None
    for p in param_grid:
        summary = run_backtest(series, p).summary()
        exp = summary.get("expectancy_pct")
        if exp is None:
            continue
        if best_summary is None or exp > best_summary.get("expectancy_pct", float("-inf")):
            best, best_summary = p, summary
    if best is None:
        best = param_grid[0]
        best_summary = run_backtest(series, best).summary()
    return best, best_summary


@dataclass
class Fold:
    train_start: str
    train_end: str
    test_start: str
    test_end: str
    best_params: Params
    train_summary: dict
    test_summary: dict
    test_trades: list[Trade] = field(default_factory=list)


@dataclass
class WalkForwardResult:
    folds: list[Fold] = field(default_factory=list)

    @property
    def combined_test_summary(self) -> dict:
        """Concatenate every fold's OOS trades — the number to trust."""
        combined = Result()
        for f in self.folds:
            combined.trades.extend(f.test_trades)
        combined.trades.sort(key=lambda t: t.entry_date)
        return combined.summary()

    @property
    def walk_forward_efficiency(self) -> float | None:
        """Mean(OOS expectancy / IS expectancy) across folds with a positive
        IS edge.

        WFE ~ 1.0 → OOS matches IS (generalizes). WFE << 1 or negative →
        the IS edge doesn't survive contact with unseen data — the classic
        overfitting signature (quantinsti/luxalgo walk-forward guidance:
        >70% is considered strong transferability). Folds where the IS
        expectancy was <= 0 are excluded — the ratio is meaningless there
        (nothing to compare against, not a case of "OOS did worse than a
        real edge"). Returns None if no fold had a positive IS edge.
        """
        ratios = []
        for f in self.folds:
            is_exp = f.train_summary.get("expectancy_pct")
            oos_exp = f.test_summary.get("expectancy_pct")
            if is_exp is None or oos_exp is None or is_exp <= 0:
                continue
            ratios.append(oos_exp / is_exp)
        return round(sum(ratios) / len(ratios), 2) if ratios else None


def walk_forward(
    series: dict[str, list[dict]],
    param_grid: list[Params],
    *,
    train_days: int = 180,
    test_days: int = 60,
    step_days: int | None = None,
) -> WalkForwardResult:
    """Roll a train/test window across the full history.

    ``train_days``/``test_days`` count bars on the shared trading calendar
    (the union of every date seen anywhere in ``series`` — KRX trading days
    are shared across all symbols, so this is exact, not an approximation).
    ``step_days`` defaults to ``test_days``: non-overlapping OOS windows, so
    no test bar is ever reused across folds and ``combined_test_summary``
    is a single clean concatenation rather than double-counted trades.

    Training bars remain available only as indicator warmup for each test
    window. Entries before test_start are forbidden, so the first OOS entry
    can use yesterday's known signal without counting an in-sample trade.

    Returns a ``WalkForwardResult`` with zero folds if the cache doesn't
    span at least one ``train_days + test_days`` window — callers must
    check ``len(result.folds)`` before trusting any aggregate.
    """
    step = step_days or test_days
    all_dates = sorted(
        {_bar_date(b) for bars in series.values() for b in bars if _bar_date(b)}
    )
    n = len(all_dates)
    folds: list[Fold] = []
    start = 0
    while start + train_days + test_days <= n:
        train_start = all_dates[start]
        train_end = all_dates[start + train_days - 1]
        test_start = all_dates[start + train_days]
        test_end = all_dates[start + train_days + test_days - 1]

        train_series = _slice_dates(series, train_start, train_end)
        test_series = _slice_dates(series, train_start, test_end)

        best_params, train_summary = _pick_best(train_series, param_grid)
        test_result = run_backtest(test_series, best_params, entry_start_date=test_start)
        folds.append(
            Fold(
                train_start=train_start,
                train_end=train_end,
                test_start=test_start,
                test_end=test_end,
                best_params=best_params,
                train_summary=train_summary,
                test_summary=test_result.summary(),
                test_trades=test_result.trades,
            )
        )
        start += step
    return WalkForwardResult(folds=folds)


# ---------------------------------------------------------------------------
# Random-entry null model — "is this alpha, or beta wearing a costume?"
# ---------------------------------------------------------------------------


@dataclass
class NullModelResult:
    strategy_expectancy: float
    null_expectancy: float        # mean across seeds of random-entry expectancy
    alpha: float                  # strategy − null
    p_value: float                # fraction of seeds that matched/beat the strategy
    n_strategy_trades: int
    n_null_trades_avg: int
    n_seeds: int

    @property
    def verdict(self) -> str:
        if self.p_value <= 0.05:
            return "🟢 진입 신호가 무작위를 유의하게 상회 (알파 가능성)"
        if self.p_value <= 0.20:
            return "🟡 미약 — 무작위 대비 우위가 불확실"
        return "🔴 무작위와 구분 안 됨 — 수익원은 진입 신호가 아니라 보유 자체(베타)"


def random_entry_null(
    series: dict[str, list[dict]],
    p: Params,
    *,
    n_seeds: int = 20,
    seed_base: int = 0,
) -> NullModelResult | None:
    """Compare a strategy against coin-flip entries under identical exits.

    The single most important control for a backtest run over one market
    regime. A rising market pays *any* strategy that holds equities, so a
    positive expectancy proves nothing on its own — the question is
    whether the entry rule beats entering at random with the same
    frequency and the same stop/take/max-hold discipline.

    Entry probability is calibrated so the null model opens roughly as
    many trades as the strategy did, keeping cost drag and sample size
    comparable. ``p_value`` is the fraction of random seeds whose
    expectancy matched or beat the strategy's: > 0.05 means the strategy
    is not distinguishable from luck.

    Interpretation trap this is designed to catch (observed 2026-07-25 on
    the live config's cache): stretching the holding period lifted net
    expectancy from +0.002% to +3.8%/trade, which looks like a discovered
    edge — but random entry earned +4.0% over the same bars. The gain was
    market drift, and the signal was contributing nothing.
    """
    strat = run_backtest(series, p).trades
    if not strat:
        return None
    strat_exp = mean(t.net_pct for t in strat)

    # Match trade count: each trade occupies ~max_hold_days bars, so this
    # entry rate reproduces the strategy's turnover (and thus its total
    # cost drag) rather than letting the null trade far more or less.
    total_bars = sum(len(b) for b in series.values())
    if total_bars <= 0:
        return None
    entry_rate = min(0.95, max(0.001, len(strat) * max(p.max_hold_days, 1) / total_bars))

    normalized = {code: normalize_rows(bars) for code, bars in series.items()}
    null_exps: list[float] = []
    null_counts: list[int] = []
    for s in range(n_seeds):
        rng = random.Random(seed_base + s)
        trades: list[Trade] = []
        for code, rows in normalized.items():
            trades.extend(
                simulate_exits(code, rows, p, lambda _r, _i: rng.random() < entry_rate)
            )
        if trades:
            null_exps.append(mean(t.net_pct for t in trades))
            null_counts.append(len(trades))
    if not null_exps:
        return None

    beat = sum(1 for x in null_exps if x >= strat_exp) / len(null_exps)
    return NullModelResult(
        strategy_expectancy=round(strat_exp, 4),
        null_expectancy=round(mean(null_exps), 4),
        alpha=round(strat_exp - mean(null_exps), 4),
        p_value=round(beat, 4),
        n_strategy_trades=len(strat),
        n_null_trades_avg=int(mean(null_counts)),
        n_seeds=len(null_exps),
    )


__all__ = [
    "Fold",
    "NullModelResult",
    "WalkForwardResult",
    "date_bounds",
    "random_entry_null",
    "split_by_date",
    "walk_forward",
]
